services:
  myportfolio:
    build: .
    restart: always
    env_file: .env
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    volumes:
      - .:/myportfolio
    depends_on:
      - mysql

  mysql:
    image: mariadb:latest
    restart: always
    env_file: .env
    volumes:
      - mydatabase:/var/lib/mysql

volumes:
  mydatabase:
